export default data = [
  {id: 0,
    length : 80,
  },
  {id: 1,
    name: 'Nom de président français'},
  {id: 2,
    name: 'Race de chien'},
  {id: 3,
    name: 'Marque de voiture'},
  {id: 4,
    name: 'Nom de fromage'},
  {id: 5,
    name: 'Mot sans "E"'},
  {id: 6,
    name: 'Pays européen'},
  {id: 7,
    name: 'Nom d\'arbre'},
  {id: 8,
    name: 'Nom de manga'},
  {id: 9,
    name: 'Moyen de locomotion'},
  {id: 10,
    name: 'Film de Tarantino'},
  {id: 11,
    name: 'Nom d\'île'},
  {id: 12,
    name: 'Animal marin'},
  {id: 13,
    name: 'Alcool'},
  {id: 14,
    name: 'Sport de ballon'},
  {id: 15,
    name: 'Maladie'},
  {id: 16,
    name: 'Philosophe'},
  {id: 17,
    name: 'Source d\'énergie'},
  {id: 18,
    name: 'Marque de téléphone'},
  {id: 19,
    name: 'Acteur français'},
  {id: 20,
    name: 'Métier'},
  {id: 21,
    name: 'Panneau de signalisation'},
  {id: 22,
    name: 'Chanteur français'},
  {id: 23,
    name: 'Console de jeu'},
  {id: 24,
    name: 'Pays d\'Afrique'},
  {id: 25,
    name: 'Nom de grande ville française'},
  {id: 26,
    name: 'Magasin alimentaire'},
  {id: 27,
    name: 'Opérateur téléphonique'},
  {id: 28,
    name: 'Equipe de Ligue 1'},
  {id: 29,
    name: 'Nom de meuble IKEA'},
  {id: 30,
    name: 'Meuble'},
  {id: 31,
    name: 'Vêtement'},
  {id: 32,
    name: 'Disney'},
  {id: 33,
    name: 'Aminal'},
  {id: 34,
    name: 'Couleur'},
  {id: 35,
    name: 'Sport'},
  {id: 36,
    name: 'Fruit'},
  {id: 37,
    name: 'Légume'},
  {id: 38,
    name: 'Ponctuation'},
  {id: 39,
    name: 'Organe'},
  {id: 40,
    name: 'Nom de mer'},
  {id: 41,
    name: 'Style de musique'},
  {id: 42,
    name: 'Chaîne de restaurant'},
  {id: 43,
    name: 'Radio'},
  {id: 44,
    name: 'Chaîne télé'},
  {id: 45,
    name: 'Série'},
  {id: 46,
    name: 'Nom de guerre'},
  {id: 47,
    name: 'Type de pâte'},
  {id: 48,
    name: 'Type d\'épice'},
  {id: 49,
    name: 'Nom de roi'},
  {id: 50,
    name: 'Nom de peintre'},
  {id: 51,
    name: 'Dessin animé'},
  {id: 52,
    name: 'Nom de peintre'},
  {id: 53,
    name: 'Animal imaginaire'},
  {id: 54,
    name: 'Sportif célèbre'},
  {id: 55,
    name: 'Jour férié'},
  {id: 56,
    name: 'Planète'},
  {id: 57,
    name: 'Marque vêtement de sport'},
  {id: 58,
    name: 'Biscuit'},
  {id: 59,
    name: 'Sauce'},
  {id: 60,
    name: 'Oiseau'},
  {id: 61,
    name: 'Jeux vidéo'},
  {id: 62,
    name: 'Instrument de musique'},
  {id: 62,
    name: 'Outils'},
  {id: 63,
    name: 'Monument célèbre'},
  {id: 64,
    name: 'Chaine de montagne'},
  {id: 65,
    name: 'Cocktails'},
  {id: 66,
    name: 'Signe astrologique'},
  {id: 67,
    name: 'Constellation'},
  {id: 68,
    name: 'Editeur de livre'},
  {id: 69,
    name: 'Marque de montre'},
  {id: 70,
    name: 'Dinausore'},
  {id: 71,
    name: 'Pizza'},
  {id: 72,
    name: 'Application de rencontre'},
  {id: 73,
    name: 'Scientifique célèbre'},
  {id: 74,
    name: 'Ville d\'Italie'},
  {id: 75,
    name: 'Ministre français'},
  {id: 76,
    name: 'Youtubeur français'},
  {id: 77,
    name: 'Tennisman'},
  {id: 78,
    name: 'Marque de moto'},
  {id: 79,
    name: 'Jeux de carte'},
  {id: 80,
    name: 'Type de danse'},
]
