export const DIMENSION_MODES = {
  IS_PORTRAIT_MOBILE_MODE: "IS_PORTRAIT_MOBILE_MODE",
  IS_PORTRAIT_SMALL_TABLET_MODE: "IS_PORTRAIT_SMALL_TABLET_MODE",
  IS_PORTRAIT_TABLET_MODE: "IS_PORTRAIT_TABLET_MODE",
  IS_LANDSCAPE_MOBILE_MODE: "IS_LANDSCAPE_MOBILE_MODE",
  IS_LANDSCAPE_TABLET_MODE: "IS_LANDSCAPE_TABLET_MODE",
};

export const TABLET_SCREEN_WIDTH = 728;
export const SMALL_SCREEN_WIDTH = 53;
